<header>
    <!--nav is seperated into top and bottom in order to more easily deal with everything-->
    <div id="navtop">
        <!--likewise, navtop is seperated into two seperate divs-->
        <div id="navtopmiddle">
            <a href="index.php"><img id="logo" src="Images/GenericITCompanyLogo.png" alt="Generic IT Company Logo"></a>
        </div>
        <aside>
            <a href="mailto:info@genericitcompany.com.au" id="contactus"><p>Contact Us!</p></a>
        </aside>
    </div>
    <nav>
        <a id="homebutton" href="index.php"><p>Home</p></a>
        <a id="applybutton" href="apply.php"><p>Apply</p></a>
        <a href="about.php"><p>About</p></a>
        <a href="jobs.php"><p>Jobs</p></a>
    </nav>
</header>